-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 12:07:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema citas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `citas` ;

-- -----------------------------------------------------
-- Schema citas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citas` DEFAULT CHARACTER SET utf8 ;
USE `citas` ;

-- -----------------------------------------------------
-- Table `citas`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`cita` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `id_paciente` INT NOT NULL,
  `id_medico` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `tipo` ENUM('presencial', 'virtual') NOT NULL DEFAULT 'presencial',
  `estado` ENUM('agendada', 'cancelada', 'realizada', 'ausente') NOT NULL DEFAULT 'agendada',
  `detalle` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas`.`horario_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`horario_medico` (
  `id_horario_medico` INT NOT NULL AUTO_INCREMENT,
  `id_medico` INT NOT NULL,
  `dia_semana` TINYINT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_horario_medico`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;