services:
  web:
    build: .
    command: gunicorn prueba.wsgi:application --bind 0.0.0.0:8003
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - db

volumes:
  postgres_data: