version: "3.9"

services:
  backend:
    image: node:18
    container_name: backend
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./srv:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb+srv://emozoarg:L1bVqyEhSAoOJXQJ@cluster0.pbqie.mongodb.net/Telemedicina"
      PORT: 3005
    command: >
      sh -c "npm install && npm run start:dev"
