version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - security-net

  security-service:
    build:
      context: .
    container_name: security-service
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - JWT_SECRET_KEY=supersecretkey
      - USER_SERVICE_URL=http://localhost:8000
    networks:
      - security-net
    depends_on:
      - redis

networks:
  security-net:
    driver: bridge
